### ISSUE TITLE
Undefined method `&' for (486311991/10):Rational

### ISSUE THREAD

**Issue by ZempTime** [mdp/rotp#49]
Hey,

I'm using `devise-two-factor` in an application, which uses this. 

When I try to log in, I get:

```ruby
NoMethodError - undefined method `&' for (486311991/10):Rational:
  rotp (2.1.1) lib/rotp/otp.rb:62:in `int_to_bytestring'
  rotp (2.1.1) lib/rotp/otp.rb:27:in `generate_otp'
  rotp (2.1.1) lib/rotp/totp.rb:23:in `at'
  devise-two-factor (2.1.0) lib/devise_two_factor/models/two_factor_authenticatable.rb:38:in `current_otp'
  app/models/user.rb:15:in `send_two_factor_authentication_code'
  app/controllers/users/sessions_controller.rb:30:in `send_2fa_code'
  actionpack (4.2.5.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  searchkick (1.2.1) lib/searchkick/logging.rb:153:in `process_action'
  activerecord (4.2.5.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/mapper.rb:49:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.2) lib/action_dispatch/routing/route_set.rb:815:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.2) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.2) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.2) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/chris/.rbenv/versions/2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/chris/.rbenv/versions/2.2.4/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/chris/.rbenv/versions/2.2.4/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Here's a more interactive look at the behavior:

<img width="660" alt="screen shot 2016-03-25 at 3 02 40 pm" src="https://cloud.githubusercontent.com/assets/3596468/14052770/acaa8914-f29a-11e5-9f61-9e94fcb17150.png">

Now, I've noticed behavior like this from another gem I'm also using: `gem 'ruby-units', '~> 2.0'`

I'm posting here because it looks like just calling `int.to_i` would fix it and someone else might run into this. But also out of some curiosity: what default behavior is being messed with here?

**Comment by ZempTime** [comment]
looks like this is related to mathn, feel free to close this if its not relevant: https://github.com/olbrich/ruby-units/issues/17

**Comment by ZempTime** [comment]
got rid of ruby-units, rewrote in unitwise and the 2fa is working flawlessly. gonna close this!
